//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonanza Interface Server.
        /// </summary>
        internal static string ConstBnziServer {
            get {
                return ResourceManager.GetString("ConstBnziServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB2.
        /// </summary>
        internal static string ConstDB2 {
            get {
                return ResourceManager.GetString("ConstDB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Windows\\SysWOW64\\config\\systemprofile\\Desktop.
        /// </summary>
        internal static string ConstExcel64Required {
            get {
                return ResourceManager.GetString("ConstExcel64Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all Product version in path.
        /// </summary>
        internal static string ConstListFileVersion {
            get {
                return ResourceManager.GetString("ConstListFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all Bonanza component in registry.
        /// </summary>
        internal static string ConstListRegisComponent {
            get {
                return ResourceManager.GetString("ConstListRegisComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register DLL.
        /// </summary>
        internal static string ConstRegDLL {
            get {
                return ResourceManager.GetString("ConstRegDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register OCX.
        /// </summary>
        internal static string ConstRegOCX {
            get {
                return ResourceManager.GetString("ConstRegOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server.
        /// </summary>
        internal static string ConstSQLServer {
            get {
                return ResourceManager.GetString("ConstSQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnRegister DLL.
        /// </summary>
        internal static string ConstUNRegDLL {
            get {
                return ResourceManager.GetString("ConstUNRegDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnRegister OCX.
        /// </summary>
        internal static string ConstUNRegOCX {
            get {
                return ResourceManager.GetString("ConstUNRegOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invest.
        /// </summary>
        internal static string DefaultDBPassword {
            get {
                return ResourceManager.GetString("DefaultDBPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invest.
        /// </summary>
        internal static string DefaultDBUsername {
            get {
                return ResourceManager.GetString("DefaultDBUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wininvest.
        /// </summary>
        internal static string DefaultWinPassword {
            get {
                return ResourceManager.GetString("DefaultWinPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wininvest.
        /// </summary>
        internal static string DefaultWinUsername {
            get {
                return ResourceManager.GetString("DefaultWinUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a config..
        /// </summary>
        internal static string ErrMsgConfig {
            get {
                return ResourceManager.GetString("ErrMsgConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ErrMsgConfirmCaption {
            get {
                return ResourceManager.GetString("ErrMsgConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ?.
        /// </summary>
        internal static string ErrMsgConfirmDelete {
            get {
                return ResourceManager.GetString("ErrMsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string ErrMsgRequired {
            get {
                return ResourceManager.GetString("ErrMsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least 1..
        /// </summary>
        internal static string ErrMsgSelectALeast {
            get {
                return ResourceManager.GetString("ErrMsgSelectALeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get specific enviroment config from database file..
        /// </summary>
        internal static string ExCannotGetSpecificEnvConfig {
            get {
                return ResourceManager.GetString("ExCannotGetSpecificEnvConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icuba6 {
            get {
                object obj = ResourceManager.GetObject("icuba6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        internal static string MsgComplete {
            get {
                return ResourceManager.GetString("MsgComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to run this script. It may change database schema and data ?.
        /// </summary>
        internal static string MsgConfirmRunScript {
            get {
                return ResourceManager.GetString("MsgConfirmRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install an Interface service..
        /// </summary>
        internal static string MsgInstallInterfaceService {
            get {
                return ResourceManager.GetString("MsgInstallInterfaceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new configuration DLL file..
        /// </summary>
        internal static string MsgRegisterDLL {
            get {
                return ResourceManager.GetString("MsgRegisterDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear configuration successfully..
        /// </summary>
        internal static string MsgTab1ClearConfig {
            get {
                return ResourceManager.GetString("MsgTab1ClearConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete configuration successfully..
        /// </summary>
        internal static string MsgTab1DeleteConfig {
            get {
                return ResourceManager.GetString("MsgTab1DeleteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load configuration complete..
        /// </summary>
        internal static string MsgTab1LoadConfig {
            get {
                return ResourceManager.GetString("MsgTab1LoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration successfully..
        /// </summary>
        internal static string MsgTab1SaveConfig {
            get {
                return ResourceManager.GetString("MsgTab1SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgTypeExclam.
        /// </summary>
        internal static string MsgTypeExclam {
            get {
                return ResourceManager.GetString("MsgTypeExclam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgTypeInfo.
        /// </summary>
        internal static string MsgTypeInfo {
            get {
                return ResourceManager.GetString("MsgTypeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall an Interface service..
        /// </summary>
        internal static string MsgUninstallInterfaceService {
            get {
                return ResourceManager.GetString("MsgUninstallInterfaceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister an old configuration DLL file..
        /// </summary>
        internal static string MsgUnregisterDLL {
            get {
                return ResourceManager.GetString("MsgUnregisterDLL", resourceCulture);
            }
        }
    }
}
